ALTER TABLE capitalization_title_plans
    ADD COLUMN type varchar,
    ADD COLUMN product_name varchar;

ALTER TABLE capitalization_title_plans_aud
    ADD COLUMN type varchar,
    ADD COLUMN product_name varchar;

ALTER TABLE capitalization_title_plan_events
    ADD COLUMN raffle_date varchar,
    ADD COLUMN raffle_settlement_date date,
    ADD COLUMN redemption_type varchar,
    ADD COLUMN redemption_request_date date,
    ADD COLUMN redemption_settlement_date date,
    ADD COLUMN raffle_amount VARCHAR,
    ADD COLUMN raffle_unit_type VARCHAR,
    ADD COLUMN raffle_unit_type_others VARCHAR,
    ADD COLUMN raffle_unit_code VARCHAR,
    ADD COLUMN raffle_unit_description VARCHAR,
    ADD COLUMN raffle_currency VARCHAR,
    ADD COLUMN redemption_amount VARCHAR,
    ADD COLUMN redemption_unit_type VARCHAR,
    ADD COLUMN redemption_unit_type_others VARCHAR,
    ADD COLUMN redemption_unit_code VARCHAR,
    ADD COLUMN redemption_unit_description VARCHAR,
    ADD COLUMN redemption_currency VARCHAR,
    ADD COLUMN redemption_bonus_amount VARCHAR,
    ADD COLUMN redemption_bonus_unit_type VARCHAR,
    ADD COLUMN redemption_bonus_unit_type_others VARCHAR,
    ADD COLUMN redemption_bonus_unit_code VARCHAR,
    ADD COLUMN redemption_bonus_unit_description VARCHAR,
    ADD COLUMN redemption_bonus_currency VARCHAR;

ALTER TABLE capitalization_title_plan_events_aud
    ADD COLUMN raffle_date varchar,
    ADD COLUMN raffle_settlement_date date,
    ADD COLUMN redemption_type varchar,
    ADD COLUMN redemption_request_date date,
    ADD COLUMN redemption_settlement_date date,
    ADD COLUMN raffle_amount VARCHAR,
    ADD COLUMN raffle_unit_type VARCHAR,
    ADD COLUMN raffle_unit_type_others VARCHAR,
    ADD COLUMN raffle_unit_code VARCHAR,
    ADD COLUMN raffle_unit_description VARCHAR,
    ADD COLUMN raffle_currency VARCHAR,
    ADD COLUMN redemption_amount VARCHAR,
    ADD COLUMN redemption_unit_type VARCHAR,
    ADD COLUMN redemption_unit_type_others VARCHAR,
    ADD COLUMN redemption_unit_code VARCHAR,
    ADD COLUMN redemption_unit_description VARCHAR,
    ADD COLUMN redemption_currency VARCHAR,
    ADD COLUMN redemption_bonus_amount VARCHAR,
    ADD COLUMN redemption_bonus_unit_type VARCHAR,
    ADD COLUMN redemption_bonus_unit_type_others VARCHAR,
    ADD COLUMN redemption_bonus_unit_code VARCHAR,
    ADD COLUMN redemption_bonus_unit_description VARCHAR,
    ADD COLUMN redemption_bonus_currency VARCHAR;

ALTER TABLE capitalization_title_plan_series
    ADD COLUMN modality varchar,
    ADD COLUMN commercial_denomination varchar,
    ADD COLUMN serie_size INTEGER,
    ADD COLUMN grace_period_redemption INTEGER,
    ADD COLUMN grace_period_for_full_redemption INTEGER,
    ADD COLUMN update_index varchar,
    ADD COLUMN update_index_others varchar,
    ADD COLUMN readjustment_index varchar,
    ADD COLUMN readjustment_index_others varchar,
    ADD COLUMN bonus_clause Boolean,
    ADD COLUMN frequency varchar,
    ADD COLUMN frequency_description varchar,
    ADD COLUMN interest_rate varchar;

ALTER TABLE capitalization_title_plan_series_aud
    ADD COLUMN modality varchar,
    ADD COLUMN commercial_denomination varchar,
    ADD COLUMN serie_size INTEGER,
    ADD COLUMN grace_period_redemption INTEGER,
    ADD COLUMN grace_period_for_full_redemption INTEGER,
    ADD COLUMN update_index varchar,
    ADD COLUMN update_index_others varchar,
    ADD COLUMN readjustment_index varchar,
    ADD COLUMN readjustment_index_others varchar,
    ADD COLUMN bonus_clause Boolean,
    ADD COLUMN frequency varchar,
    ADD COLUMN frequency_description varchar,
    ADD COLUMN interest_rate varchar;

ALTER TABLE capitalization_title_plan_settlements
    ADD COLUMN settlement_financial_amount VARCHAR,
    ADD COLUMN settlement_financial_unit_type VARCHAR,
    ADD COLUMN settlement_financial_unit_type_others VARCHAR,
    ADD COLUMN settlement_financial_unit_code VARCHAR,
    ADD COLUMN settlement_financial_unit_description VARCHAR,
    ADD COLUMN settlement_financial_currency VARCHAR,
    ADD COLUMN settlement_payment_date date,
    ADD COLUMN settlement_due_date date;

ALTER TABLE capitalization_title_plan_settlements_aud
    ADD COLUMN settlement_financial_amount VARCHAR,
    ADD COLUMN settlement_financial_unit_type VARCHAR,
    ADD COLUMN settlement_financial_unit_type_others VARCHAR,
    ADD COLUMN settlement_financial_unit_code VARCHAR,
    ADD COLUMN settlement_financial_unit_description VARCHAR,
    ADD COLUMN settlement_financial_currency VARCHAR,
    ADD COLUMN settlement_payment_date date,
    ADD COLUMN settlement_due_date date;

CREATE TABLE capitalization_title_plan_titles (
    capitalization_title_plan_title_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    registration_form VARCHAR,
    issue_title_date DATE,
    term_start_date DATE,
    term_end_date DATE,
    raffle_premium_amount VARCHAR,
    raffle_premium_unit_type VARCHAR,
    raffle_premium_unit_type_others VARCHAR,
    raffle_premium_unit_code VARCHAR,
    raffle_premium_unit_description VARCHAR,
    raffle_premium_currency VARCHAR,
    contribution_amount VARCHAR,
    contribution_unit_type VARCHAR,
    contribution_unit_type_others VARCHAR,
    contribution_unit_code VARCHAR,
    contribution_unit_description VARCHAR,
    contribution_currency VARCHAR,
    capitalization_title_plan_series_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_series_id) REFERENCES capitalization_title_plan_series (capitalization_title_plan_series_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_titles_aud (
    capitalization_title_plan_title_id UUID,
    registration_form VARCHAR,
    issue_title_date DATE,
    term_start_date DATE,
    term_end_date DATE,
    raffle_premium_amount VARCHAR,
    raffle_premium_unit_type VARCHAR,
    raffle_premium_unit_type_others VARCHAR,
    raffle_premium_unit_code VARCHAR,
    raffle_premium_unit_description VARCHAR,
    raffle_premium_currency VARCHAR,
    contribution_amount VARCHAR,
    contribution_unit_type VARCHAR,
    contribution_unit_type_others VARCHAR,
    contribution_unit_code VARCHAR,
    contribution_unit_description VARCHAR,
    contribution_currency VARCHAR,
    capitalization_title_plan_series_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_title_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE capitalization_title_plan_technical_provisions (
    capitalization_title_plan_technical_provision_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    capitalization_title_plan_title_id UUID,
    pmc_amount VARCHAR,
    pmc_unit_type VARCHAR,
    pmc_unit_type_others VARCHAR,
    pmc_unit_code VARCHAR,
    pmc_unit_description VARCHAR,
    pmc_currency VARCHAR,
    pdb_amount VARCHAR,
    pdb_unit_type VARCHAR,
    pdb_unit_type_others VARCHAR,
    pdb_unit_code VARCHAR,
    pdb_unit_description VARCHAR,
    pdb_currency VARCHAR,
    pr_amount VARCHAR,
    pr_unit_type VARCHAR,
    pr_unit_type_others VARCHAR,
    pr_unit_code VARCHAR,
    pr_unit_description VARCHAR,
    pr_currency VARCHAR,
    psp_amount VARCHAR,
    psp_unit_type VARCHAR,
    psp_unit_type_others VARCHAR,
    psp_unit_code VARCHAR,
    psp_unit_description VARCHAR,
    psp_currency VARCHAR,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_title_id) REFERENCES capitalization_title_plan_titles (capitalization_title_plan_title_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_technical_provisions_aud (
    capitalization_title_plan_technical_provision_id UUID,
    capitalization_title_plan_title_id UUID,
    pmc_amount VARCHAR,
    pmc_unit_type VARCHAR,
    pmc_unit_type_others VARCHAR,
    pmc_unit_code VARCHAR,
    pmc_unit_description VARCHAR,
    pmc_currency VARCHAR,
    pdb_amount VARCHAR,
    pdb_unit_type VARCHAR,
    pdb_unit_type_others VARCHAR,
    pdb_unit_code VARCHAR,
    pdb_unit_description VARCHAR,
    pdb_currency VARCHAR,
    pr_amount VARCHAR,
    pr_unit_type VARCHAR,
    pr_unit_type_others VARCHAR,
    pr_unit_code VARCHAR,
    pr_unit_description VARCHAR,
    pr_currency VARCHAR,
    psp_amount VARCHAR,
    psp_unit_type VARCHAR,
    psp_unit_type_others VARCHAR,
    psp_unit_code VARCHAR,
    psp_unit_description VARCHAR,
    psp_currency VARCHAR,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_technical_provision_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE capitalization_title_plan_brokers (
    capitalization_title_plan_broker_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    susep_broker_code VARCHAR,
    broker_description VARCHAR,
    capitalization_title_plan_series_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_series_id) REFERENCES capitalization_title_plan_series (capitalization_title_plan_series_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_brokers_aud (
    capitalization_title_plan_broker_id UUID,
    susep_broker_code VARCHAR,
    broker_description VARCHAR,
    capitalization_title_plan_series_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_broker_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE capitalization_title_plan_quotas (
    capitalization_title_plan_quota_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    quota INTEGER,
    capitalization_quota VARCHAR,
    raffle_quota VARCHAR,
    charging_quota VARCHAR,
    capitalization_title_plan_series_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_series_id) REFERENCES capitalization_title_plan_series (capitalization_title_plan_series_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_quotas_aud (
    capitalization_title_plan_quota_id UUID,
    quota INTEGER,
    capitalization_quota VARCHAR,
    raffle_quota VARCHAR,
    charging_quota VARCHAR,
    capitalization_title_plan_series_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_quota_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE capitalization_title_plan_subscribers (
    capitalization_title_plan_subscriber_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    subscriber_name VARCHAR,
    subscriber_document_type VARCHAR,
    subscriber_document_type_others VARCHAR,
    subscriber_document_number VARCHAR,
    subscriber_country_calling_code VARCHAR,
    subscriber_area_code VARCHAR,
    subscriber_number VARCHAR,
    subscriber_address VARCHAR,
    subscriber_address_additional_info VARCHAR,
    subscriber_town_name VARCHAR,
    subscriber_country_sub_division VARCHAR,
    subscriber_country_code VARCHAR,
    subscriber_postcode VARCHAR,
    capitalization_title_plan_title_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_title_id) REFERENCES capitalization_title_plan_titles (capitalization_title_plan_title_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_subscribers_aud (
    capitalization_title_plan_subscriber_id UUID,
    subscriber_name VARCHAR,
    subscriber_document_type VARCHAR,
    subscriber_document_type_others VARCHAR,
    subscriber_document_number VARCHAR,
    subscriber_country_calling_code VARCHAR,
    subscriber_area_code VARCHAR,
    subscriber_number VARCHAR,
    subscriber_address VARCHAR,
    subscriber_address_additional_info VARCHAR,
    subscriber_town_name VARCHAR,
    subscriber_country_sub_division VARCHAR,
    subscriber_country_code VARCHAR,
    subscriber_postcode VARCHAR,
    capitalization_title_plan_title_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_subscriber_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE capitalization_title_plan_holders (
    capitalization_title_plan_holder_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    holder_name VARCHAR,
    holder_document_type VARCHAR,
    holder_document_type_others VARCHAR,
    holder_document_number VARCHAR,
    holder_country_calling_code VARCHAR,
    holder_area_code VARCHAR,
    holder_number VARCHAR,
    holder_address VARCHAR,
    holder_address_additional_info VARCHAR,
    holder_town_name VARCHAR,
    holder_country_subdivision VARCHAR,
    holder_country_code VARCHAR,
    holder_postcode VARCHAR,
    holder_redemption Boolean,
    holder_raffle Boolean,
    capitalization_title_plan_subscriber_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (capitalization_title_plan_subscriber_id) REFERENCES capitalization_title_plan_subscribers (capitalization_title_plan_subscriber_id) ON DELETE CASCADE
);

CREATE TABLE capitalization_title_plan_holders_aud (
    capitalization_title_plan_holder_id UUID,
    holder_name VARCHAR,
    holder_document_type VARCHAR,
    holder_document_type_others VARCHAR,
    holder_document_number VARCHAR,
    holder_country_calling_code VARCHAR,
    holder_area_code VARCHAR,
    holder_number VARCHAR,
    holder_address VARCHAR,
    holder_address_additional_info VARCHAR,
    holder_town_name VARCHAR,
    holder_country_subdivision VARCHAR,
    holder_country_code VARCHAR,
    holder_postcode VARCHAR,
    holder_redemption Boolean,
    holder_raffle Boolean,
    capitalization_title_plan_subscriber_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (capitalization_title_plan_holder_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);