ALTER TABLE financial_assistance_contracts
    ADD COLUMN certificate_id varchar,
    ADD COLUMN group_contract_id varchar,
    ADD COLUMN susep_process_number varchar,
    ADD COLUMN conceived_credit_value_amount varchar,
    ADD COLUMN conceived_credit_value_unit_type varchar,
    ADD COLUMN conceived_credit_value_unit_type_others varchar,
    ADD COLUMN conceived_credit_value_unit_code varchar,
    ADD COLUMN conceived_credit_value_unit_description varchar,
    ADD COLUMN conceived_credit_value_currency varchar,
    ADD COLUMN credited_liquid_value_amount varchar,
    ADD COLUMN credited_liquid_value_unit_type varchar,
    ADD COLUMN credited_liquid_value_unit_type_others varchar,
    ADD COLUMN credited_liquid_value_unit_code varchar,
    ADD COLUMN credited_liquid_value_unit_description varchar,
    ADD COLUMN credited_liquid_value_currency varchar,
    ADD COLUMN counter_installment_amount varchar,
    ADD COLUMN counter_installment_unit_type varchar,
    ADD COLUMN counter_installment_unit_type_others varchar,
    ADD COLUMN counter_installment_unit_code varchar,
    ADD COLUMN counter_installment_unit_description varchar,
    ADD COLUMN counter_installment_currency varchar,
    ADD COLUMN counter_installment_periodicity varchar,
    ADD COLUMN counter_installment_quantity int,
    ADD COLUMN counter_installment_first_date date,
    ADD COLUMN counter_installment_last_date date,
    ADD COLUMN interest_rate_amount varchar,
    ADD COLUMN interest_rate_unit_type varchar,
    ADD COLUMN interest_rate_unit_type_others varchar,
    ADD COLUMN interest_rate_unit_code varchar,
    ADD COLUMN interest_rate_unit_description varchar,
    ADD COLUMN interest_rate_currency varchar,
    ADD COLUMN effective_cost_rate_amount varchar,
    ADD COLUMN effective_cost_rate_unit_type varchar,
    ADD COLUMN effective_cost_rate_unit_type_others varchar,
    ADD COLUMN effective_cost_rate_unit_code varchar,
    ADD COLUMN effective_cost_rate_unit_description varchar,
    ADD COLUMN effective_cost_rate_currency varchar,
    ADD COLUMN amortization_period int,
    ADD COLUMN acquittance_value_amount varchar,
    ADD COLUMN acquittance_value_unit_type varchar,
    ADD COLUMN acquittance_value_unit_type_others varchar,
    ADD COLUMN acquittance_value_unit_code varchar,
    ADD COLUMN acquittance_value_unit_description varchar,
    ADD COLUMN acquittance_value_currency varchar,
    ADD COLUMN acquittance_date date,
    ADD COLUMN taxes_value_amount varchar,
    ADD COLUMN taxes_value_unit_type varchar,
    ADD COLUMN taxes_value_unit_type_others varchar,
    ADD COLUMN taxes_value_unit_code varchar,
    ADD COLUMN taxes_value_unit_description varchar,
    ADD COLUMN taxes_value_currency varchar,
    ADD COLUMN expenses_value_amount varchar,
    ADD COLUMN expenses_value_unit_type varchar,
    ADD COLUMN expenses_value_unit_type_others varchar,
    ADD COLUMN expenses_value_unit_code varchar,
    ADD COLUMN expenses_value_unit_description varchar,
    ADD COLUMN expenses_value_currency varchar,
    ADD COLUMN fines_value_amount varchar,
    ADD COLUMN fines_value_unit_type varchar,
    ADD COLUMN fines_value_unit_type_others varchar,
    ADD COLUMN fines_value_unit_code varchar,
    ADD COLUMN fines_value_unit_description varchar,
    ADD COLUMN fines_value_currency varchar,
    ADD COLUMN monetary_updates_value_amount varchar,
    ADD COLUMN monetary_updates_value_unit_type varchar,
    ADD COLUMN monetary_updates_value_unit_type_others varchar,
    ADD COLUMN monetary_updates_value_unit_code varchar,
    ADD COLUMN monetary_updates_value_unit_description varchar,
    ADD COLUMN monetary_updates_value_currency varchar,
    ADD COLUMN administrative_fees_value_amount varchar,
    ADD COLUMN administrative_fees_value_unit_type varchar,
    ADD COLUMN administrative_fees_value_unit_type_others varchar,
    ADD COLUMN administrative_fees_value_unit_code varchar,
    ADD COLUMN administrative_fees_value_unit_description varchar,
    ADD COLUMN administrative_fees_value_currency varchar,
    ADD COLUMN interest_value_amount varchar,
    ADD COLUMN interest_value_unit_type varchar,
    ADD COLUMN interest_value_unit_type_others varchar,
    ADD COLUMN interest_value_unit_code varchar,
    ADD COLUMN interest_value_unit_description varchar,
    ADD COLUMN interest_value_currency varchar;

ALTER TABLE financial_assistance_contracts_aud
    ADD COLUMN certificate_id varchar,
    ADD COLUMN group_contract_id varchar,
    ADD COLUMN susep_process_number varchar,
    ADD COLUMN conceived_credit_value_amount varchar,
    ADD COLUMN conceived_credit_value_unit_type varchar,
    ADD COLUMN conceived_credit_value_unit_type_others varchar,
    ADD COLUMN conceived_credit_value_unit_code varchar,
    ADD COLUMN conceived_credit_value_unit_description varchar,
    ADD COLUMN conceived_credit_value_currency varchar,
    ADD COLUMN credited_liquid_value_amount varchar,
    ADD COLUMN credited_liquid_value_unit_type varchar,
    ADD COLUMN credited_liquid_value_unit_type_others varchar,
    ADD COLUMN credited_liquid_value_unit_code varchar,
    ADD COLUMN credited_liquid_value_unit_description varchar,
    ADD COLUMN credited_liquid_value_currency varchar,
    ADD COLUMN counter_installment_amount varchar,
    ADD COLUMN counter_installment_unit_type varchar,
    ADD COLUMN counter_installment_unit_type_others varchar,
    ADD COLUMN counter_installment_unit_code varchar,
    ADD COLUMN counter_installment_unit_description varchar,
    ADD COLUMN counter_installment_currency varchar,
    ADD COLUMN counter_installment_periodicity varchar,
    ADD COLUMN counter_installment_quantity int,
    ADD COLUMN counter_installment_first_date date,
    ADD COLUMN counter_installment_last_date date,
    ADD COLUMN interest_rate_amount varchar,
    ADD COLUMN interest_rate_unit_type varchar,
    ADD COLUMN interest_rate_unit_type_others varchar,
    ADD COLUMN interest_rate_unit_code varchar,
    ADD COLUMN interest_rate_unit_description varchar,
    ADD COLUMN interest_rate_currency varchar,
    ADD COLUMN effective_cost_rate_amount varchar,
    ADD COLUMN effective_cost_rate_unit_type varchar,
    ADD COLUMN effective_cost_rate_unit_type_others varchar,
    ADD COLUMN effective_cost_rate_unit_code varchar,
    ADD COLUMN effective_cost_rate_unit_description varchar,
    ADD COLUMN effective_cost_rate_currency varchar,
    ADD COLUMN amortization_period int,
    ADD COLUMN acquittance_value_amount varchar,
    ADD COLUMN acquittance_value_unit_type varchar,
    ADD COLUMN acquittance_value_unit_type_others varchar,
    ADD COLUMN acquittance_value_unit_code varchar,
    ADD COLUMN acquittance_value_unit_description varchar,
    ADD COLUMN acquittance_value_currency varchar,
    ADD COLUMN acquittance_date date,
    ADD COLUMN taxes_value_amount varchar,
    ADD COLUMN taxes_value_unit_type varchar,
    ADD COLUMN taxes_value_unit_type_others varchar,
    ADD COLUMN taxes_value_unit_code varchar,
    ADD COLUMN taxes_value_unit_description varchar,
    ADD COLUMN taxes_value_currency varchar,
    ADD COLUMN expenses_value_amount varchar,
    ADD COLUMN expenses_value_unit_type varchar,
    ADD COLUMN expenses_value_unit_type_others varchar,
    ADD COLUMN expenses_value_unit_code varchar,
    ADD COLUMN expenses_value_unit_description varchar,
    ADD COLUMN expenses_value_currency varchar,
    ADD COLUMN fines_value_amount varchar,
    ADD COLUMN fines_value_unit_type varchar,
    ADD COLUMN fines_value_unit_type_others varchar,
    ADD COLUMN fines_value_unit_code varchar,
    ADD COLUMN fines_value_unit_description varchar,
    ADD COLUMN fines_value_currency varchar,
    ADD COLUMN monetary_updates_value_amount varchar,
    ADD COLUMN monetary_updates_value_unit_type varchar,
    ADD COLUMN monetary_updates_value_unit_type_others varchar,
    ADD COLUMN monetary_updates_value_unit_code varchar,
    ADD COLUMN monetary_updates_value_unit_description varchar,
    ADD COLUMN monetary_updates_value_currency varchar,
    ADD COLUMN administrative_fees_value_amount varchar,
    ADD COLUMN administrative_fees_value_unit_type varchar,
    ADD COLUMN administrative_fees_value_unit_type_others varchar,
    ADD COLUMN administrative_fees_value_unit_code varchar,
    ADD COLUMN administrative_fees_value_unit_description varchar,
    ADD COLUMN administrative_fees_value_currency varchar,
    ADD COLUMN interest_value_amount varchar,
    ADD COLUMN interest_value_unit_type varchar,
    ADD COLUMN interest_value_unit_type_others varchar,
    ADD COLUMN interest_value_unit_code varchar,
    ADD COLUMN interest_value_unit_description varchar,
    ADD COLUMN interest_value_currency varchar;

ALTER TABLE financial_assistance_contract_movements
    ADD COLUMN updated_debit_amount VARCHAR,
    ADD COLUMN updated_debit_unit_type VARCHAR,
    ADD COLUMN updated_debit_unit_type_others VARCHAR,
    ADD COLUMN updated_debit_unit_code VARCHAR,
    ADD COLUMN updated_debit_unit_description VARCHAR,
    ADD COLUMN updated_debit_currency VARCHAR,
    ADD COLUMN remaining_counter_installments_quantity INTEGER,
    ADD COLUMN remaining_unpaid_counter_installments_quantity INTEGER,
    ADD COLUMN life_pension_pm_bac_amount VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_type VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_type_others VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_code VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_description VARCHAR,
    ADD COLUMN life_pension_pm_bac_currency VARCHAR,
    ADD COLUMN pension_plan_pm_bac_amount VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_type VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_type_others VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_code VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_description VARCHAR,
    ADD COLUMN pension_plan_pm_bac_currency VARCHAR;

ALTER TABLE financial_assistance_contract_movements_aud
    ADD COLUMN updated_debit_amount VARCHAR,
    ADD COLUMN updated_debit_unit_type VARCHAR,
    ADD COLUMN updated_debit_unit_type_others VARCHAR,
    ADD COLUMN updated_debit_unit_code VARCHAR,
    ADD COLUMN updated_debit_unit_description VARCHAR,
    ADD COLUMN updated_debit_currency VARCHAR,
    ADD COLUMN remaining_counter_installments_quantity INTEGER,
    ADD COLUMN remaining_unpaid_counter_installments_quantity INTEGER,
    ADD COLUMN life_pension_pm_bac_amount VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_type VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_type_others VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_code VARCHAR,
    ADD COLUMN life_pension_pm_bac_unit_description VARCHAR,
    ADD COLUMN life_pension_pm_bac_currency VARCHAR,
    ADD COLUMN pension_plan_pm_bac_amount VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_type VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_type_others VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_code VARCHAR,
    ADD COLUMN pension_plan_pm_bac_unit_description VARCHAR,
    ADD COLUMN pension_plan_pm_bac_currency VARCHAR;

CREATE TABLE financial_assistance_contract_insureds (
    financial_assistance_contract_insured_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    document_type VARCHAR,
    document_type_others VARCHAR,
    document_number VARCHAR,
    name VARCHAR,
    financial_assistance_contract_id VARCHAR,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (financial_assistance_contract_id) REFERENCES financial_assistance_contracts (financial_assistance_contract_id) ON DELETE CASCADE
);

CREATE TABLE financial_assistance_contract_insureds_aud (
    financial_assistance_contract_insured_id UUID,
    document_type VARCHAR,
    document_type_others VARCHAR,
    document_number VARCHAR,
    name VARCHAR,
    financial_assistance_contract_id VARCHAR,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (financial_assistance_contract_insured_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);