ALTER TABLE life_pension_contracts
    ADD COLUMN product_name VARCHAR,
    ADD COLUMN product_code VARCHAR,
    ADD COLUMN conjugated_plan BOOLEAN,
    ADD COLUMN proposal_id VARCHAR,
    ADD COLUMN certificate_active BOOLEAN,
    ADD COLUMN contracting_type VARCHAR,
    ADD COLUMN contract_id VARCHAR,
    ADD COLUMN plan_type VARCHAR,
    ADD COLUMN effective_date_start DATE,
    ADD COLUMN effective_date_end DATE,
    ADD COLUMN periodicity VARCHAR,
    ADD COLUMN tax_regime VARCHAR,
    ADD COLUMN insured_document_type VARCHAR,
    ADD COLUMN insured_document_number VARCHAR,
    ADD COLUMN insured_name VARCHAR,
    ADD COLUMN insured_birth_date DATE,
    ADD COLUMN insured_gender VARCHAR,
    ADD COLUMN insured_post_code VARCHAR,
    ADD COLUMN insured_town_name VARCHAR,
    ADD COLUMN insured_country_sub_division VARCHAR,
    ADD COLUMN insured_country_code VARCHAR,
    ADD COLUMN insured_address VARCHAR,
    ADD COLUMN insured_district_name VARCHAR,
    ADD COLUMN insured_ibge_town_code VARCHAR,
    ADD COLUMN insured_address_name VARCHAR,
    ADD COLUMN insured_address_number VARCHAR,
    ADD COLUMN insured_address_complementary_info VARCHAR,
    ADD COLUMN insured_address_type VARCHAR,
    ADD COLUMN insured_address_flag_post_code VARCHAR;

ALTER TABLE life_pension_contracts_aud
    ADD COLUMN product_name VARCHAR,
    ADD COLUMN product_code VARCHAR,
    ADD COLUMN conjugated_plan BOOLEAN,
    ADD COLUMN proposal_id VARCHAR,
    ADD COLUMN certificate_active BOOLEAN,
    ADD COLUMN contracting_type VARCHAR,
    ADD COLUMN contract_id VARCHAR,
    ADD COLUMN plan_type VARCHAR,
    ADD COLUMN effective_date_start DATE,
    ADD COLUMN effective_date_end DATE,
    ADD COLUMN periodicity VARCHAR,
    ADD COLUMN tax_regime VARCHAR,
    ADD COLUMN insured_document_type VARCHAR,
    ADD COLUMN insured_document_number VARCHAR,
    ADD COLUMN insured_name VARCHAR,
    ADD COLUMN insured_birth_date DATE,
    ADD COLUMN insured_gender VARCHAR,
    ADD COLUMN insured_post_code VARCHAR,
    ADD COLUMN insured_town_name VARCHAR,
    ADD COLUMN insured_country_sub_division VARCHAR,
    ADD COLUMN insured_country_code VARCHAR,
    ADD COLUMN insured_address VARCHAR,
    ADD COLUMN insured_district_name VARCHAR,
    ADD COLUMN insured_ibge_town_code VARCHAR,
    ADD COLUMN insured_address_name VARCHAR,
    ADD COLUMN insured_address_number VARCHAR,
    ADD COLUMN insured_address_complementary_info VARCHAR,
    ADD COLUMN insured_address_type VARCHAR,
    ADD COLUMN insured_address_flag_post_code VARCHAR;

CREATE TABLE life_pension_contract_suseps (
    life_pension_contract_susep_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    coverage_code VARCHAR,
    susep_process_number VARCHAR,
    structure_modality VARCHAR,
    type VARCHAR,
    locked_plan BOOLEAN,
    qualified_proposer BOOLEAN,
    benefit_payment_method VARCHAR,
    financial_result_reversal BOOLEAN,
    calculation_basis VARCHAR,
    life_pension_contract_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (life_pension_contract_id) REFERENCES life_pension_contracts (life_pension_contract_id) ON DELETE CASCADE
);

CREATE TABLE life_pension_contract_suseps_aud (
    life_pension_contract_susep_id UUID,
    coverage_code VARCHAR,
    susep_process_number VARCHAR,
    structure_modality VARCHAR,
    type VARCHAR,
    locked_plan BOOLEAN,
    qualified_proposer BOOLEAN,
    benefit_payment_method VARCHAR,
    financial_result_reversal BOOLEAN,
    calculation_basis VARCHAR,
    life_pension_contract_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (life_pension_contract_susep_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE life_pension_contract_susep_fies (
    life_pension_contract_susep_fie_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    fie_cnpj VARCHAR,
    fie_name VARCHAR,
    fie_trade_name VARCHAR,
    pmbac_amount VARCHAR,
    pmbac_unit_type VARCHAR,
    pmbac_unit_type_others VARCHAR,
    pmbac_unit_code VARCHAR,
    pmbac_unit_description VARCHAR,
    pmbac_currency VARCHAR,
    provision_surplus_amount VARCHAR,
    provision_surplus_unit_type VARCHAR,
    provision_surplus_unit_type_others VARCHAR,
    provision_surplus_unit_code VARCHAR,
    provision_surplus_unit_description VARCHAR,
    provision_surplus_currency VARCHAR,
    life_pension_contract_susep_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (life_pension_contract_susep_id) REFERENCES life_pension_contract_suseps (life_pension_contract_susep_id) ON DELETE CASCADE
);

CREATE TABLE life_pension_contract_susep_fies_aud (
    life_pension_contract_susep_fie_id UUID,
    fie_cnpj VARCHAR,
    fie_name VARCHAR,
    fie_trade_name VARCHAR,
    pmbac_amount VARCHAR,
    pmbac_unit_type VARCHAR,
    pmbac_unit_type_others VARCHAR,
    pmbac_unit_code VARCHAR,
    pmbac_unit_description VARCHAR,
    pmbac_currency VARCHAR,
    provision_surplus_amount VARCHAR,
    provision_surplus_unit_type VARCHAR,
    provision_surplus_unit_type_others VARCHAR,
    provision_surplus_unit_code VARCHAR,
    provision_surplus_unit_description VARCHAR,
    provision_surplus_currency VARCHAR,
    life_pension_contract_susep_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (life_pension_contract_susep_fie_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
