CREATE TABLE patrimonial_insured_objects (
    patrimonial_insured_object_id                               UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    policy_id                                                   UUID,
    identification                                              VARCHAR,
    type                                                        VARCHAR,
    description                                                 VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (policy_id) REFERENCES patrimonial_policies (policy_id) ON DELETE CASCADE
);

CREATE TABLE patrimonial_insured_objects_aud (
    patrimonial_insured_object_id                               UUID,
    policy_id                                                   UUID,
    identification                                              VARCHAR,
    type                                                        VARCHAR,
    description                                                 VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (patrimonial_insured_object_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE patrimonial_insured_object_coverages (
    patrimonial_insured_object_coverage_id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    patrimonial_insured_object_id                               UUID,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_unit_code                                               VARCHAR,
    lmi_unit_description                                        VARCHAR,
    lmi_sublimit                                                BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    main_coverage                                               BOOLEAN,
    feature                                                     VARCHAR,
    type                                                        VARCHAR,
    grace_period                                                INTEGER,
    grace_periodicity                                           VARCHAR,
    grace_period_counting_method                                VARCHAR,
    grace_period_start_date                                     DATE,
    grace_period_end_date                                       DATE,
    premium_periodicity                                         VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (patrimonial_insured_object_id) REFERENCES patrimonial_insured_objects (patrimonial_insured_object_id) ON DELETE CASCADE
);

CREATE TABLE patrimonial_insured_object_coverages_aud (
    patrimonial_insured_object_coverage_id                      UUID,
    patrimonial_insured_object_id                               UUID,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_unit_code                                               VARCHAR,
    lmi_unit_description                                        VARCHAR,
    lmi_sublimit                                                BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    main_coverage                                               BOOLEAN,
    feature                                                     VARCHAR,
    type                                                        VARCHAR,
    grace_period                                                INTEGER,
    grace_periodicity                                           VARCHAR,
    grace_period_counting_method                                VARCHAR,
    grace_period_start_date                                     DATE,
    grace_period_end_date                                       DATE,
    premium_periodicity                                         VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (patrimonial_insured_object_coverage_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
