ALTER TABLE pension_plan_contract_withdrawals
    ADD COLUMN withdrawal_occurence BOOLEAN,
    ADD COLUMN type VARCHAR,
    ADD COLUMN nature VARCHAR,
    ADD COLUMN request_date VARCHAR,
    ADD COLUMN liquidation_date VARCHAR,
    ADD COLUMN amount VARCHAR,
    ADD COLUMN amount_unit_type VARCHAR,
    ADD COLUMN amount_unit_type_others VARCHAR,
    ADD COLUMN amount_unit_code VARCHAR,
    ADD COLUMN amount_unit_description VARCHAR,
    ADD COLUMN amount_currency VARCHAR,
    ADD COLUMN posted_charged_amount VARCHAR,
    ADD COLUMN posted_charged_unit_type VARCHAR,
    ADD COLUMN posted_charged_unit_type_others VARCHAR,
    ADD COLUMN posted_charged_unit_code VARCHAR,
    ADD COLUMN posted_charged_unit_description VARCHAR,
    ADD COLUMN posted_charged_currency VARCHAR;

ALTER TABLE pension_plan_contract_withdrawals_aud
    ADD COLUMN withdrawal_occurence BOOLEAN,
    ADD COLUMN type VARCHAR,
    ADD COLUMN nature VARCHAR,
    ADD COLUMN request_date VARCHAR,
    ADD COLUMN liquidation_date VARCHAR,
    ADD COLUMN amount VARCHAR,
    ADD COLUMN amount_unit_type VARCHAR,
    ADD COLUMN amount_unit_type_others VARCHAR,
    ADD COLUMN amount_unit_code VARCHAR,
    ADD COLUMN amount_unit_description VARCHAR,
    ADD COLUMN amount_currency VARCHAR,
    ADD COLUMN posted_charged_amount VARCHAR,
    ADD COLUMN posted_charged_unit_type VARCHAR,
    ADD COLUMN posted_charged_unit_type_others VARCHAR,
    ADD COLUMN posted_charged_unit_code VARCHAR,
    ADD COLUMN posted_charged_unit_description VARCHAR,
    ADD COLUMN posted_charged_currency VARCHAR;
