ALTER TABLE pension_plan_contracts
    ADD COLUMN contracting_type VARCHAR;

ALTER TABLE pension_plan_contracts_aud
    ADD COLUMN contracting_type VARCHAR;

CREATE TABLE pension_plan_contract_documents (
    pension_plan_contract_document_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    certificate_id VARCHAR,
    effective_date_start DATE,
    effective_date_end DATE,
    proposal_id VARCHAR,
    pension_plan_contract_id VARCHAR,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (pension_plan_contract_id) REFERENCES pension_plan_contracts (pension_plan_contract_id) ON DELETE CASCADE
);

CREATE TABLE pension_plan_contract_documents_aud (
    pension_plan_contract_document_id UUID,
    certificate_id VARCHAR,
    effective_date_start DATE,
    effective_date_end DATE,
    proposal_id VARCHAR,
    pension_plan_contract_id VARCHAR,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (pension_plan_contract_document_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE pension_plan_contract_document_insureds (
    pension_plan_contract_document_insured_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    document_type VARCHAR,
    document_number VARCHAR,
    name VARCHAR,
    birth_date DATE,
    gender VARCHAR,
    post_code VARCHAR,
    town_name VARCHAR,
    country_sub_division VARCHAR,
    country_code VARCHAR,
    address VARCHAR,
    district_name VARCHAR,
    ibge_town_code VARCHAR,
    address_name VARCHAR,
    address_number VARCHAR,
    address_complementary_info VARCHAR,
    address_type VARCHAR,
    flag_post_code VARCHAR,
    pension_plan_contract_document_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (pension_plan_contract_document_id) REFERENCES pension_plan_contract_documents (pension_plan_contract_document_id) ON DELETE CASCADE
);

CREATE TABLE pension_plan_contract_document_insureds_aud (
    pension_plan_contract_document_insured_id UUID,
    document_type VARCHAR,
    document_number VARCHAR,
    name VARCHAR,
    birth_date DATE,
    gender VARCHAR,
    post_code VARCHAR,
    town_name VARCHAR,
    country_sub_division VARCHAR,
    country_code VARCHAR,
    address VARCHAR,
    district_name VARCHAR,
    ibge_town_code VARCHAR,
    address_name VARCHAR,
    address_number VARCHAR,
    address_complementary_info VARCHAR,
    address_type VARCHAR,
    flag_post_code VARCHAR,
    pension_plan_contract_document_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (pension_plan_contract_document_insured_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE pension_plan_contract_document_coverages (
    pension_plan_contract_document_coverage_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    coverage_code VARCHAR,
    susep_process_number VARCHAR,
    structure_modality VARCHAR,
    benefit_amount VARCHAR,
    benefit_amount_unit_type VARCHAR,
    periodicity VARCHAR,
    coverage_name VARCHAR,
    locked_plan BOOLEAN,
    term_start_date DATE,
    term_end_date DATE,
    financial_regime VARCHAR,
    pricing_method VARCHAR,
    update_index VARCHAR,
    update_index_lagging INTEGER,
    contribution_amount VARCHAR,
    contribution_amount_unit_type VARCHAR,
    benefit_payment_amount VARCHAR,
    benefit_payment_amount_unit_type VARCHAR,
    benefit_payment_method VARCHAR,
    charged_amount VARCHAR,
    charged_amount_unit_type VARCHAR,
    pension_plan_contract_document_id UUID,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    FOREIGN KEY (pension_plan_contract_document_id) REFERENCES pension_plan_contract_documents (pension_plan_contract_document_id) ON DELETE CASCADE
);

CREATE TABLE pension_plan_contract_document_coverages_aud (
    pension_plan_contract_document_coverage_id UUID,
    coverage_code VARCHAR,
    susep_process_number VARCHAR,
    structure_modality VARCHAR,
    benefit_amount VARCHAR,
    benefit_amount_unit_type VARCHAR,
    periodicity VARCHAR,
    coverage_name VARCHAR,
    locked_plan BOOLEAN,
    term_start_date DATE,
    term_end_date DATE,
    financial_regime VARCHAR,
    pricing_method VARCHAR,
    update_index VARCHAR,
    update_index_lagging INTEGER,
    contribution_amount VARCHAR,
    contribution_amount_unit_type VARCHAR,
    benefit_payment_amount VARCHAR,
    benefit_payment_amount_unit_type VARCHAR,
    benefit_payment_method VARCHAR,
    charged_amount VARCHAR,
    charged_amount_unit_type VARCHAR,
    pension_plan_contract_document_id UUID,
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    created_at           TIMESTAMP,
    created_by           VARCHAR,
    updated_at           TIMESTAMP,
    updated_by           VARCHAR,
    hibernate_status     VARCHAR,
    PRIMARY KEY (pension_plan_contract_document_coverage_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
