ALTER TABLE person_policies
ADD COLUMN product_name VARCHAR,
ADD COLUMN document_type VARCHAR,
ADD COLUMN susep_process_number VARCHAR,
ADD COLUMN group_certificate_id VARCHAR,
ADD COLUMN issuance_type VARCHAR,
ADD COLUMN issuance_date DATE,
ADD COLUMN term_start_date DATE,
ADD COLUMN term_end_date DATE,
ADD COLUMN lead_insurer_code VARCHAR,
ADD COLUMN lead_insurer_policy_id VARCHAR,
ADD COLUMN proposal_id VARCHAR,
ADD COLUMN pmbac_amount VARCHAR,
ADD COLUMN pmbac_unit_type VARCHAR,
ADD COLUMN pmbac_unit_code VARCHAR,
ADD COLUMN pmbac_unit_description VARCHAR,
ADD COLUMN occurrence_withdrawal BOOLEAN,
ADD COLUMN occurrence_portability BOOLEAN;

ALTER TABLE person_policies_aud
ADD COLUMN product_name VARCHAR,
ADD COLUMN document_type VARCHAR,
ADD COLUMN susep_process_number VARCHAR,
ADD COLUMN group_certificate_id VARCHAR,
ADD COLUMN issuance_type VARCHAR,
ADD COLUMN issuance_date DATE,
ADD COLUMN term_start_date DATE,
ADD COLUMN term_end_date DATE,
ADD COLUMN lead_insurer_code VARCHAR,
ADD COLUMN lead_insurer_policy_id VARCHAR,
ADD COLUMN proposal_id VARCHAR,
ADD COLUMN pmbac_amount VARCHAR,
ADD COLUMN pmbac_unit_type VARCHAR,
ADD COLUMN pmbac_unit_code VARCHAR,
ADD COLUMN pmbac_unit_description VARCHAR,
ADD COLUMN occurrence_withdrawal BOOLEAN,
ADD COLUMN occurrence_portability BOOLEAN;
