CREATE TABLE person_insured_objects (
    person_insured_object_id                                    UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    person_policy_id                                            UUID,
    type                                                        VARCHAR,
    description                                                 VARCHAR,
    amount                                                      VARCHAR,
    unit_type                                                   VARCHAR,
    unit_code                                                   VARCHAR,
    unit_description                                            VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (person_policy_id) REFERENCES person_policies (person_policy_id) ON DELETE CASCADE
);

CREATE TABLE person_insured_objects_aud (
    person_insured_object_id                                    UUID,
    person_policy_id                                            UUID,
    type                                                        VARCHAR,
    description                                                 VARCHAR,
    amount                                                      VARCHAR,
    unit_type                                                   VARCHAR,
    unit_code                                                   VARCHAR,
    unit_description                                            VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (person_insured_object_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE person_insured_object_coverages (
    person_insured_object_coverage_id                           UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    person_insured_object_id                                    UUID,
    type                                                        VARCHAR,
    feature                                                     VARCHAR,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    description                                                 VARCHAR,
    internal_code                                               VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_sublimit                                                BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    main_coverage                                               BOOLEAN,
    trigger_event                                               VARCHAR,
    financial_type                                              VARCHAR,
    benefit_payment_modality                                    VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (person_insured_object_id) REFERENCES person_insured_objects (person_insured_object_id) ON DELETE CASCADE
);

CREATE TABLE person_insured_object_coverages_aud (
    person_insured_object_coverage_id                           UUID,
    person_insured_object_id                                    UUID,
    type                                                        VARCHAR,
    feature                                                     VARCHAR,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    description                                                 VARCHAR,
    internal_code                                               VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_sublimit                                                BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    main_coverage                                               BOOLEAN,
    trigger_event                                               VARCHAR,
    financial_type                                              VARCHAR,
    benefit_payment_modality                                    VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (person_insured_object_coverage_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
