CREATE TABLE transport_policy_insured_objects (
    transport_policy_insured_object_id                          UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    transport_policy_id                                         VARCHAR,
    identification                                              VARCHAR,
    type                                                        VARCHAR,
    type_additional_info                                        VARCHAR,
    description                                                 VARCHAR,
    amount                                                      VARCHAR,
    unit_type                                                   VARCHAR,
    unit_type_others                                            VARCHAR,
    unit_code                                                   VARCHAR,
    unit_description                                            VARCHAR,
    currency                                                    VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (transport_policy_id) REFERENCES transport_policies (transport_policy_id) ON DELETE CASCADE
);

CREATE TABLE transport_policy_insured_objects_aud (
    transport_policy_insured_object_id                          UUID,
    transport_policy_id                                         VARCHAR,
    identification                                              VARCHAR,
    type                                                        VARCHAR,
    type_additional_info                                        VARCHAR,
    description                                                 VARCHAR,
    amount                                                      VARCHAR,
    unit_type                                                   VARCHAR,
    unit_type_others                                            VARCHAR,
    unit_code                                                   VARCHAR,
    unit_description                                            VARCHAR,
    currency                                                    VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (transport_policy_insured_object_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE transport_policy_insured_object_coverages (
    transport_policy_insured_object_coverage_id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    transport_policy_insured_object_id                          UUID,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    description                                                 VARCHAR,
    internal_code                                               VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_unit_type_others                                        VARCHAR,
    lmi_unit_code                                               VARCHAR,
    lmi_unit_description                                        VARCHAR,
    lmi_currency                                                VARCHAR,
    is_lmi_sublimit                                             BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    is_main_coverage                                            BOOLEAN,
    feature                                                     VARCHAR,
    type                                                        VARCHAR,
    grace_period                                                INTEGER,
    grace_periodicity                                           VARCHAR,
    grace_period_counting_method                                VARCHAR,
    grace_period_start_date                                     DATE,
    grace_period_end_date                                       DATE,
    premium_periodicity                                         VARCHAR,
    premium_periodicity_others                                  VARCHAR,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    FOREIGN KEY (transport_policy_insured_object_id) REFERENCES transport_policy_insured_objects (transport_policy_insured_object_id) ON DELETE CASCADE
);

CREATE TABLE transport_policy_insured_object_coverages_aud (
    transport_policy_insured_object_coverage_id                 UUID,
    transport_policy_insured_object_id                          UUID,
    branch                                                      VARCHAR,
    code                                                        VARCHAR,
    description                                                 VARCHAR,
    internal_code                                               VARCHAR,
    susep_process_number                                        VARCHAR,
    lmi_amount                                                  VARCHAR,
    lmi_unit_type                                               VARCHAR,
    lmi_unit_type_others                                        VARCHAR,
    lmi_unit_code                                               VARCHAR,
    lmi_unit_description                                        VARCHAR,
    lmi_currency                                                VARCHAR,
    is_lmi_sublimit                                             BOOLEAN,
    term_start_date                                             DATE,
    term_end_date                                               DATE,
    is_main_coverage                                            BOOLEAN,
    feature                                                     VARCHAR,
    type                                                        VARCHAR,
    grace_period                                                INTEGER,
    grace_periodicity                                           VARCHAR,
    grace_period_counting_method                                VARCHAR,
    grace_period_start_date                                     DATE,
    grace_period_end_date                                       DATE,
    premium_periodicity                                         VARCHAR,
    premium_periodicity_others                                  VARCHAR,
    rev                                                         INTEGER NOT NULL,
    revtype                                                     SMALLINT,
    created_at                                                  TIMESTAMP,
    created_by                                                  VARCHAR,
    updated_at                                                  TIMESTAMP,
    updated_by                                                  VARCHAR,
    hibernate_status                                            VARCHAR,
    PRIMARY KEY (transport_policy_insured_object_coverage_id, rev),
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
