import io.micronaut.gradle.MicronautRuntime
import io.micronaut.gradle.MicronautTestRuntime

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id "application"
    id 'jacoco'
    id 'groovy'
    id 'maven-publish'
    id "org.sonarqube" version "7.3.1.8318"
    id "org.owasp.dependencycheck" version "8.4.0"
    id "io.micronaut.application" version "4.6.2"
    id "io.micronaut.aot" version "4.6.2"
}

def props = new Properties()
file("version.properties").withInputStream { props.load(it) }
String buildNumber = System.getenv("BUILD_NUMBER")

String swaggerVersion = "1.2.0.2"

version = System.getenv("CHANGE_ID") ? "${props.VERSION}-SNAPSHOT" : "${props.VERSION}.${buildNumber}"
group "com.raidiam.trustframework.mockinsurance"
dependencyCheck {
    formats = ['HTML', 'XML']
}
tasks.shadowJar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    mergeServiceFiles()
    archiveClassifier = null

    dependencies {
        exclude(dependency('org.apache.logging.log4j:.*.*'))
    }

    minimize {
        exclude(dependency('io.micronaut.*:.*'))
        exclude(dependency('org.hibernate.*:.*'))
        exclude(dependency('software.amazon.awssdk:.*'))
        exclude(dependency('com.amazonaws:.*'))
        exclude(dependency('io.hypersistence:.*'))
        exclude(dependency('org.bouncycastle:.*'))
        exclude(dependency('org.flywaydb:.*'))
        exclude(dependency('ch.qos.*:.*'))
        exclude(dependency('net.logstash.*:.*'))
        exclude(dependency('org.yaml:.*'))
        exclude(dependency('software.amazon.jdbc:.*'))
    }
}

tasks.withType(Jar).configureEach {
    zip64 = true
}

configurations.configureEach {
    exclude group: 'software.amazon.awssdk', module: 'apache-client'
    exclude group: 'software.amazon.awssdk', module: 'netty-nio-client'
}

def shadowDependents = [
        "mergeServiceFilesForOptimizedNativeJar",
        "distTar",
        "startScripts",
        "prepareJitOptimizations",
        "prepareNativeOptimizations"
]

tasks.matching { it.name in shadowDependents }.configureEach {
    dependsOn tasks.named("shadowJar")
}

tasks.matching { it.name == "startShadowScripts" }.configureEach {
    dependsOn(tasks.named("jar"))
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

micronaut {
    version "4.10.12"
    runtime MicronautRuntime.LAMBDA_JAVA
    runtime MicronautRuntime.LAMBDA_PROVIDED
    runtime MicronautRuntime.NETTY
    testRuntime MicronautTestRuntime.SPOCK_2
    processing {
        incremental(true)
        annotations("com.raidiam.trustframework.mockinsurance.*")
    }

    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}

dependencies {

    runtimeOnly "org.yaml:snakeyaml"

    // https://mvnrepository.com/artifact/io.projectreactor/reactor-core
    implementation group: 'io.projectreactor', name: 'reactor-core', version: '3.8.0'

    //These must be above the micronaut stuff, so lombok can generate the boilerplate
    //for micronaut/hibernate to look at
    implementation 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    implementation platform('com.amazonaws:aws-java-sdk-bom:1.12.793')
    implementation platform('com.amazonaws:aws-xray-recorder-sdk-bom:2.20.0')

    annotationProcessor "io.micronaut.data:micronaut-data-processor"
    annotationProcessor "io.micronaut.validation:micronaut-validation-processor"
    annotationProcessor "io.micronaut.security:micronaut-security-annotations"
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut:micronaut-http-validation"

    implementation 'com.nimbusds:nimbus-jose-jwt:9.40'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.82'
    implementation 'org.postgresql:postgresql'
    implementation "io.micronaut.security:micronaut-security"
    implementation "com.google.guava:guava:33.5.0-jre"
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.28'

    implementation 'software.amazon.awssdk:url-connection-client:2.38.6'
    // Required on the classpath for the AWS Advanced JDBC Wrapper's IAM auth plugin
    implementation 'software.amazon.awssdk:rds:2.38.6'
    // Required on the classpath for the AWS Advanced JDBC Wrapper's Secrets Manager plugin
    implementation 'software.amazon.awssdk:secretsmanager:2.38.6'
    implementation 'software.amazon.jdbc:aws-advanced-jdbc-wrapper:4.1.0'

    implementation("com.raidiam.trustframework.mockinsurance:insurance-swagger:${swaggerVersion}") {
        changing = true
    }

    implementation 'com.amazonaws:aws-java-sdk-api-gateway'
    runtimeOnly("com.amazonaws:aws-xray-recorder-sdk-core")
    runtimeOnly("com.amazonaws:aws-xray-recorder-sdk-aws-sdk")
    runtimeOnly("com.amazonaws:aws-xray-recorder-sdk-aws-sdk-instrumentor")
    runtimeOnly("com.amazonaws:aws-xray-recorder-sdk-sql-postgres")

    runtimeOnly 'org.jlib:jlib-awslambda-logback:1.0.0'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    compileOnly 'ch.qos.logback:logback-classic'

    implementation("io.micronaut.aws:micronaut-function-aws")
    implementation 'io.micronaut.aws:micronaut-function-aws-custom-runtime'
    implementation 'io.micronaut.aws:micronaut-function-aws-api-proxy'

    developmentOnly "io.micronaut:micronaut-http-server-netty"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut:micronaut-inject"
    implementation "io.micronaut.validation:micronaut-validation"
    implementation 'io.micronaut.data:micronaut-data-hibernate-jpa'
    implementation 'io.micronaut.data:micronaut-data-tx-hibernate'
    implementation 'io.micronaut.sql:micronaut-hibernate-jpa'
    implementation "io.micronaut.flyway:micronaut-flyway"
    implementation 'io.micronaut.sql:micronaut-jdbc-tomcat'
    // https://mvnrepository.com/artifact/io.hypersistence/hypersistence-utils-hibernate-63
    implementation group: 'io.hypersistence', name: 'hypersistence-utils-hibernate-63', version: '3.12.0'
    // update to rxjava3 at some point
    implementation 'io.micronaut.rxjava2:micronaut-rxjava2'
    implementation 'io.micronaut.rxjava2:micronaut-rxjava2-http-client'

    implementation 'org.hibernate.orm:hibernate-envers:6.6.13.Final'

    implementation 'io.micronaut:micronaut-runtime'

    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.1"

    implementation 'org.json:json:20240303'

    // force versions for dep check
    implementation 'commons-io:commons-io:2.21.0'

    implementation 'com.github.mvallim:emv-qrcode:0.1.2'

    // https://mvnrepository.com/artifact/com.webauthn4j/webauthn4j-core
    implementation 'com.webauthn4j:webauthn4j-core:0.30.0.RELEASE'


    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    implementation("io.micronaut:micronaut-jackson-databind")

    implementation("io.micronaut.beanvalidation:micronaut-hibernate-validator")

    implementation("io.micronaut:micronaut-context-propagation")

    // -- TEST DEPS

    runtimeOnly 'org.fusesource.jansi:jansi:1.18'

    testAnnotationProcessor 'io.micronaut:micronaut-inject-groovy'
    testImplementation "com.amazonaws:aws-java-sdk-core"
    testImplementation "io.micronaut.test:micronaut-test-spock"
    testImplementation "io.micronaut:micronaut-inject-groovy"

    testImplementation "org.objenesis:objenesis:3.4"

    testImplementation(platform("org.testcontainers:testcontainers-bom:2.0.2"))
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:testcontainers-spock'
    testImplementation 'org.testcontainers:testcontainers-localstack'
    testImplementation 'org.testcontainers:testcontainers-postgresql'

    testImplementation 'org.mock-server:mockserver-netty:5.15.0'
    testImplementation 'org.mock-server:mockserver-client-java:5.15.0'
    testImplementation 'org.mock-server:mockserver-junit-jupiter:5.15.0'
    testImplementation 'org.mock-server:mockserver-junit-rule:5.15.0'
    testImplementation 'ch.qos.logback:logback-classic'

    testImplementation "com.h2database:h2"

   // testImplementation 'com.amazonaws.serverless:aws-serverless-java-container-core:1.9.4'
}

test.outputs.upToDateWhen { false }

test {
    useJUnitPlatform()
    beforeTest { descriptor ->
        logger.lifecycle("Running test: ${descriptor}")
    }
    classpath += configurations.developmentOnly
    environment "AWS_XRAY_CONTEXT_MISSING", "LOG_ERROR"
    finalizedBy jacocoTestReport
    maxParallelForks = 2
    jacoco {
        excludes = ['com.raidiam.trustframework.bank.models.*']
    }
    testLogging {
        events "started", "passed", "skipped", "failed"
    }
    minHeapSize = "512m"
    maxHeapSize = "6144m"
}

application {
    mainClass = "com.raidiam.trustframework.mockinsurance.Application"
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add('-parameters')
}

run {
    classpath += configurations.developmentOnly
    jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
}


graalvmNative.toolchainDetection = false

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    'com/raidiam/trustframework/mockinsurance/models/**'
            ])
        }))
    }
    reports {
        xml.required.set true
    }
}
