package com.raidiam.trustframework.mockinsurance.enums;

public enum ResourceType {


    CUSTOMERS_PERSONAL_IDENTIFICATIONS,
    CUSTOMERS_PERSONAL_QUALIFICATION,
    CUSTOMERS_PERSONAL_ADDITIONALINFO,
    CUSTOMERS_BUSINESS_IDENTIFICATIONS,
    CUSTOMERS_BUSINESS_QUALIFICATION,
    CUSTOMERS_BUSINESS_ADDITIONALINFO,
    CAPITALIZATION_TITLES,
    PENSION_PLAN,
    LIFE_PENSION,
    FINANCIAL_ASSISTANCE,
    DAMAGES_AND_PEOPLE_PATRIMONIAL,
    DAMAGES_AND_PEOPLE_RESPONSIBILITY,
    DAMAGES_AND_PEOPLE_TRANSPORT,
    DAMAGES_AND_PEOPLE_FINANCIAL_RISKS,
    DAMAGES_AND_PEOPLE_RURAL,
    DAMAGES_AND_PEOPLE_AUTO,
    DAMAGES_AND_PEOPLE_HOUSING,
    DAMAGES_AND_PEOPLE_PERSON,
    DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD;


    @Override
    public String toString() {
        return this.name();
    }
}
