package com.raidiam.trustframework.mockinsurance.utils;

import com.raidiam.trustframework.mockinsurance.models.generated.EnumConsentV3Permission;

import java.util.EnumSet;
import java.util.List;
import java.util.Set;

public enum PermissionV3Phase {
    PHASE2(EnumSet.of(
            EnumConsentV3Permission.RESOURCES_READ,
            EnumConsentV3Permission.CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ,
            EnumConsentV3Permission.CUSTOMERS_PERSONAL_QUALIFICATION_READ,
            EnumConsentV3Permission.CUSTOMERS_PERSONAL_ADDITIONALINFO_READ,
            EnumConsentV3Permission.CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ,
            EnumConsentV3Permission.CUSTOMERS_BUSINESS_QUALIFICATION_READ,
            EnumConsentV3Permission.CUSTOMERS_BUSINESS_ADDITIONALINFO_READ,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_READ,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_PLANINFO_READ,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_EVENTS_READ,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_SETTLEMENTS_READ,
            EnumConsentV3Permission.PENSION_PLAN_READ,
            EnumConsentV3Permission.PENSION_PLAN_CONTRACTINFO_READ,
            EnumConsentV3Permission.PENSION_PLAN_MOVEMENTS_READ,
            EnumConsentV3Permission.PENSION_PLAN_PORTABILITIES_READ,
            EnumConsentV3Permission.PENSION_PLAN_WITHDRAWALS_READ,
            EnumConsentV3Permission.PENSION_PLAN_CLAIM_READ,
            EnumConsentV3Permission.LIFE_PENSION_READ,
            EnumConsentV3Permission.LIFE_PENSION_CONTRACTINFO_READ,
            EnumConsentV3Permission.LIFE_PENSION_MOVEMENTS_READ,
            EnumConsentV3Permission.LIFE_PENSION_PORTABILITIES_READ,
            EnumConsentV3Permission.LIFE_PENSION_WITHDRAWALS_READ,
            EnumConsentV3Permission.LIFE_PENSION_CLAIM_READ,
            EnumConsentV3Permission.FINANCIAL_ASSISTANCE_READ,
            EnumConsentV3Permission.FINANCIAL_ASSISTANCE_CONTRACTINFO_READ,
            EnumConsentV3Permission.FINANCIAL_ASSISTANCE_MOVEMENTS_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PATRIMONIAL_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PATRIMONIAL_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PATRIMONIAL_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PATRIMONIAL_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RESPONSIBILITY_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RESPONSIBILITY_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RESPONSIBILITY_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RESPONSIBILITY_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_TRANSPORT_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_TRANSPORT_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_TRANSPORT_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_TRANSPORT_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RURAL_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RURAL_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RURAL_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_RURAL_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_AUTO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_AUTO_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_AUTO_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_AUTO_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_HOUSING_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_HOUSING_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_HOUSING_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_HOUSING_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_CLAIM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PERSON_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PERSON_POLICYINFO_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PERSON_PREMIUM_READ,
            EnumConsentV3Permission.DAMAGES_AND_PEOPLE_PERSON_CLAIM_READ
    )),

    PHASE3(EnumSet.of(
            EnumConsentV3Permission.CLAIM_NOTIFICATION_REQUEST_DAMAGE_CREATE,
            EnumConsentV3Permission.CLAIM_NOTIFICATION_REQUEST_PERSON_CREATE,
            EnumConsentV3Permission.ENDORSEMENT_REQUEST_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_HOME_READ,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_HOME_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_HOME_UPDATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_CONDOMINIUM_READ,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_BUSINESS_READ,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_BUSINESS_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_BUSINESS_UPDATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE,
            EnumConsentV3Permission.QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE,
            EnumConsentV3Permission.QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_AUTO_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_AUTO_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_AUTO_READ,
            EnumConsentV3Permission.QUOTE_AUTO_CREATE,
            EnumConsentV3Permission.QUOTE_AUTO_UPDATE,
            EnumConsentV3Permission.QUOTE_FINANCIAL_RISK_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_FINANCIAL_RISK_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_HOUSING_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_HOUSING_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_RESPONSIBILITY_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_RESPONSIBILITY_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_RURAL_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_RURAL_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_TRANSPORT_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_TRANSPORT_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_PERSON_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_PERSON_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_PERSON_LIFE_READ,
            EnumConsentV3Permission.QUOTE_PERSON_LIFE_CREATE,
            EnumConsentV3Permission.QUOTE_PERSON_LIFE_UPDATE,
            EnumConsentV3Permission.QUOTE_PERSON_TRAVEL_READ,
            EnumConsentV3Permission.QUOTE_PERSON_TRAVEL_CREATE,
            EnumConsentV3Permission.QUOTE_PERSON_TRAVEL_UPDATE,
            EnumConsentV3Permission.QUOTE_CAPITALIZATION_TITLE_LEAD_CREATE,
            EnumConsentV3Permission.QUOTE_CAPITALIZATION_TITLE_LEAD_UPDATE,
            EnumConsentV3Permission.QUOTE_CAPITALIZATION_TITLE_READ,
            EnumConsentV3Permission.QUOTE_CAPITALIZATION_TITLE_CREATE,
            EnumConsentV3Permission.QUOTE_CAPITALIZATION_TITLE_UPDATE,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_RAFFLE_CREATE,
            EnumConsentV3Permission.CONTRACT_PENSION_PLAN_LEAD_CREATE,
            EnumConsentV3Permission.CONTRACT_PENSION_PLAN_LEAD_UPDATE,
            EnumConsentV3Permission.CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_CREATE,
            EnumConsentV3Permission.CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_UPDATE,
            EnumConsentV3Permission.CONTRACT_LIFE_PENSION_LEAD_CREATE,
            EnumConsentV3Permission.CONTRACT_LIFE_PENSION_LEAD_UPDATE,
            EnumConsentV3Permission.CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_CREATE,
            EnumConsentV3Permission.CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_UPDATE,
            EnumConsentV3Permission.PENSION_WITHDRAWAL_CREATE,
            EnumConsentV3Permission.CAPITALIZATION_TITLE_WITHDRAWAL_CREATE
    ));

    private final Set<EnumConsentV3Permission> permissions;

    PermissionV3Phase(Set<EnumConsentV3Permission> permissions) {
        this.permissions = permissions;
    }

    public boolean containsAny(List<EnumConsentV3Permission> permissions) {
        return permissions.stream().anyMatch(this.permissions::contains);
    }
}
